name: pharmacy-main

networks:
  pharmacy_databases:
    external: true
  broker:
    name: pharmacy_broker
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:4.2.5-management-alpine
    hostname: ${RABBITMQ_HOST}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PANEL_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - broker

  public-api:
    build:
      context: .
      dockerfile: ./pharmacy-api/docker-files/public-api.go.dockerfile
    ports:
      - "${PUBLIC_API_PORT}:8080"
    volumes:
      - ./pharmacy-api/pharmacy-content:/public-api/shared/pharmacy-content
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}

      TZ: ${TZ}

    networks:
      - pharmacy_databases
      - broker
  
  local-api:
    build:
      context: .
      dockerfile: ./pharmacy-api/docker-files/local-api.go.dockerfile
    ports:
      - "${LOCAL_API_PORT}:8080"
    volumes:
        - ./pharmacy-api/pharmacy-content:/local-api/shared/pharmacy-content
    environment:
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}

      ACCESSTOKEN_SECRET: ${ACCESSTOKEN_SECRET}
      REFRESHTOKEN_SECRET: ${REFRESHTOKEN_SECRET}

      CONTROL_PANEL_ADMIN_LOGIN: ${CONTROL_PANEL_ADMIN_LOGIN}
      CONTROL_PANEL_ADMIN_PASSWORD: ${CONTROL_PANEL_ADMIN_PASSWORD}

      TZ: ${TZ}

    networks:
      - pharmacy_databases
      - broker

  public-frontend:
    build:
      context: .
      dockerfile: ./pharmacy-public-frontend/dockerfile
    ports:
      - "${PUBLIC_FRONTEND_PORT}:80"
    
  local-frontend:
    build:
      context: .
      dockerfile: ./pharmacy-local-frontend/dockerfile
    ports:
      - "${LOCAL_FRONTEND_PORT}:80"

volumes:
  rabbitmq_data:
