name: pharmacy-services

networks:
  pharmacy_databases:
    external: true
  pharmacy_broker:
    external: true

services:
  goods_service:
    build:
      context: .
      dockerfile: ./pharmacy-api/src/services/goods_service/goods_service.dockerfile
    volumes:
      - ./pharmacy-api/pharmacy-content:/app/pharmacy-content
    environment:
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    networks:
      - pharmacy_databases
      - pharmacy_broker

  schedule_service:
    build:
      context: .
      dockerfile: ./pharmacy-api/src/services/schedule_service/schedule_service.dockerfile
    volumes:
       - ./pharmacy-api/pharmacy-content:/app/pharmacy-content
    environment:
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    networks:
      - pharmacy_databases
      - pharmacy_broker

#   orders_service:
#     build:
#       context: .
#       dockerfile: ./pharmacy-api/services/orders_service/orders_service.go.dockerfile
#     volumes:
#        - ./pharmacy-api/pharmacy-content:/service/shared/pharmacy-content
#     environment:
#       DB_HOST: ${DATABASE_HOST}
#       DB_PORT: ${DATABASE_PORT}
#       DB_USER: ${DATABASE_USER}
#       DB_PASSWORD: ${DATABASE_PASSWORD}
#       DB_NAME: ${DATABASE_NAME}
#       REDIS_HOST: ${REDIS_HOST}
#       REDIS_PORT: ${REDIS_PORT}
#       REDIS_PASSWORD: ${REDIS_PASSWORD}
#       RABBITMQ_USER: ${RABBITMQ_USER}
#       RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
#       RABBITMQ_HOST: ${RABBITMQ_HOST}
#     networks:
#       - pharmacy_databases
#       - pharmacy_broker
  
#   announces_service:
#     build:
#       context: .
#       dockerfile: ./pharmacy-api/services/announces_service/announces_service.go.dockerfile
#     volumes:
#        - ./pharmacy-api/pharmacy-content:/service/shared/pharmacy-content
#     environment:
#       DB_HOST: ${DATABASE_HOST}
#       DB_PORT: ${DATABASE_PORT}
#       DB_USER: ${DATABASE_USER}
#       DB_PASSWORD: ${DATABASE_PASSWORD}
#       DB_NAME: ${DATABASE_NAME}
#       REDIS_HOST: ${REDIS_HOST}
#       REDIS_PORT: ${REDIS_PORT}
#       REDIS_PASSWORD: ${REDIS_PASSWORD}
#       RABBITMQ_USER: ${RABBITMQ_USER}
#       RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
#       RABBITMQ_HOST: ${RABBITMQ_HOST}
#     networks:
#       - pharmacy_databases
#       - pharmacy_broker

#   users_service:
#     build:
#       context: .
#       dockerfile: ./pharmacy-api/services/users_service/users_service.go.dockerfile
#     volumes:
#        - ./pharmacy-api/pharmacy-content:/service/shared/pharmacy-content
#     environment:
#       DB_HOST: ${DATABASE_HOST}
#       DB_PORT: ${DATABASE_PORT}
#       DB_USER: ${DATABASE_USER}
#       DB_PASSWORD: ${DATABASE_PASSWORD}
#       DB_NAME: ${DATABASE_NAME}
#       REDIS_HOST: ${REDIS_HOST}
#       REDIS_PORT: ${REDIS_PORT}
#       REDIS_PASSWORD: ${REDIS_PASSWORD}
#       RABBITMQ_USER: ${RABBITMQ_USER}
#       RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
#       RABBITMQ_HOST: ${RABBITMQ_HOST}
#     networks:
#       - pharmacy_databases
#       - pharmacy_broker

#   roles_service:
#     build:
#       context: .
#       dockerfile: ./pharmacy-api/services/roles_service/roles_service.go.dockerfile
#     volumes:
#        - ./pharmacy-api/pharmacy-content:/service/shared/pharmacy-content
#     environment:
#       DB_HOST: ${DATABASE_HOST}
#       DB_PORT: ${DATABASE_PORT}
#       DB_USER: ${DATABASE_USER}
#       DB_PASSWORD: ${DATABASE_PASSWORD}
#       DB_NAME: ${DATABASE_NAME}
#       REDIS_HOST: ${REDIS_HOST}
#       REDIS_PORT: ${REDIS_PORT}
#       REDIS_PASSWORD: ${REDIS_PASSWORD}
#       RABBITMQ_USER: ${RABBITMQ_USER}
#       RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
#       RABBITMQ_HOST: ${RABBITMQ_HOST}
#     networks:
#       - pharmacy_databases
#       - pharmacy_broker