FROM oven/bun:latest AS build-stage

WORKDIR /app

COPY pharmacy-local-frontend/package.json pharmacy-local-frontend/bun.lock ./
RUN bun install

COPY pharmacy-local-frontend/. .
RUN bun run build

FROM nginx:stable-alpine AS production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]